### ISSUE TITLE
stack_func(nullptr) crushes

### ISSUE THREAD

**Issue by asssh52** [RTCupid/Stack#1]
<img width="240" alt="image" src="https://github.com/user-attachments/assets/fe383aed-fcf7-4b1e-8b3e-d2080321c67a">
<img width="244" alt="image" src="https://github.com/user-attachments/assets/ddd134c2-73bb-431f-b467-cd83f8cfa202">

despite verification failing in "verificator" you are still trying to dump nullptr

**Comment by RTCupid** [comment]
Thank you, I fixed this bug.
<img width="175" alt="image" src="https://github.com/user-attachments/assets/79505277-6f85-494c-890a-281117b67581">
<img width="420" alt="image" src="https://github.com/user-attachments/assets/cf06c4b1-e59d-4e06-829b-5268175b88df">
