### ISSUE TITLE
stackpop(&stack, nullptr) crushes

### ISSUE THREAD

**Issue by asssh52** [RTCupid/Stack#2]
<img width="281" alt="image" src="https://github.com/user-attachments/assets/071dd0d6-c2ec-4b42-8819-62ed9718c1c9">
<img width="274" alt="image" src="https://github.com/user-attachments/assets/7c863ff4-e3d7-4421-acfc-8cd804d32cba">
there is no checks if variable pointer is correct

**Comment by RTCupid** [comment]
OK, thank you for your issue. I fixed this bug. Now if you send the nullptr param to the function, it will not be executed.
<img width="115" alt="image" src="https://github.com/user-attachments/assets/2ac38139-3b5d-40e5-8c45-26670f09938f">
<img width="342" alt="image" src="https://github.com/user-attachments/assets/817bfd3d-1f52-42ca-bfb8-85ee9db961af">
And now you can output this error to the console using the function PrintErrorStack (err_t error, const char* namefnc).
<img width="166" alt="image" src="https://github.com/user-attachments/assets/1916543c-6033-4d65-9432-f2d51a0a2c11">
<img width="410" alt="image" src="https://github.com/user-attachments/assets/21101a67-0bdd-454e-a14c-79070e7b2c73">
